# Generated by Django 2.2 on 2019-04-07 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('assessment', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Curator')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Curator')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32, null=True)),
                ('photo', models.FilePathField(null=True, path='/front/assets/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Ball')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Curator')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Diploma')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Group')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Work')),
            ],
        ),
    ]
