# Generated by Django 2.2 on 2019-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FilePathField(null=True, path='/front/assets/image'),
        ),
    ]
