# Generated by Django 2.2 on 2019-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190418_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FilePathField(null=True, path='/assets/image'),
        ),
    ]
