# Generated by Django 2.2 on 2019-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20190418_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FilePathField(null=True, path='assets/image'),
        ),
    ]
