# Generated by Django 2.2 on 2019-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20190418_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FilePathField(null=True, path='/home/woolf/Workspace/python/graduates/static/assets/image'),
        ),
    ]
