# Generated by Django 2.2 on 2019-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20190420_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='photo',
            field=models.ImageField(blank=True, default='/assets/image/default.png', upload_to='assets/image'),
        ),
    ]
