# Generated by Django 2.2 on 2019-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20190420_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='photo',
            field=models.ImageField(blank=True, default='static/assets/image/default.png', upload_to='static/assets/image'),
        ),
    ]
