# Generated by Django 2.2 on 2019-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20190420_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ManyToManyField(to='crud.Faculty'),
        ),
    ]
