# Generated by Django 2.2 on 2019-04-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20190420_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='crud.Faculty'),
        ),
    ]
