# Generated by Django 2.2 on 2019-04-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20190420_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='crud.Curator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='static/assets/image/default.png', upload_to='static/assets/image'),
        ),
    ]
