# Generated by Django 2.2 on 2019-04-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_auto_20190421_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ball',
        ),
        migrations.AddField(
            model_name='student',
            name='ball',
            field=models.ManyToManyField(related_name='balls', to='crud.Ball'),
        ),
        migrations.AlterField(
            model_name='student',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='crud.Work'),
        ),
    ]
