# Generated by Django 2.2 on 2019-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_auto_20190421_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ball',
            field=models.ManyToManyField(related_name='ball', to='crud.Ball'),
        ),
    ]
