# Generated by Django 2.2 on 2019-04-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_auto_20190421_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_end',
            field=models.IntegerField(default=2019),
        ),
    ]
