# Generated by Django 2.2 on 2019-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_student_year_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
