# Generated by Django 2.2 on 2019-05-05 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_student_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='subject',
        ),
        migrations.AddField(
            model_name='ball',
            name='math',
            field=models.IntegerField(default='60', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='ball',
            name='physical',
            field=models.IntegerField(default='60', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='ball',
            name='programing',
            field=models.IntegerField(default='60', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(60)]),
        ),
        migrations.RemoveField(
            model_name='student',
            name='ball',
        ),
        migrations.AddField(
            model_name='student',
            name='ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ball', to='crud.Ball'),
        ),
    ]
